"use strict";
const COLS=10,ROWS=20,BLOCK=30;
const COLORS={I:"#22d3ee",J:"#3b82f6",L:"#f97316",O:"#facc15",S:"#22c55e",T:"#8b5cf6",Z:"#ec4899"};
const SHAPES={I:[[1,1,1,1]],J:[[1,0,0],[1,1,1]],L:[[0,0,1],[1,1,1]],O:[[1,1],[1,1]],S:[[0,1,1],[1,1,0]],T:[[0,1,0],[1,1,1]],Z:[[1,1,0],[0,1,1]]};
const canvas=document.getElementById("gameCanvas"),ctx=canvas.getContext("2d"),nextCanvas=document.getElementById("nextCanvas"),nextCtx=nextCanvas.getContext("2d");
const scoreValue=document.getElementById("scoreValue"),levelValue=document.getElementById("levelValue"),linesValue=document.getElementById("linesValue"),highScoreValue=document.getElementById("highScoreValue"),overlay=document.getElementById("overlay"),overlayTitle=document.getElementById("overlayTitle"),overlayText=document.getElementById("overlayText"),startButton=document.getElementById("startButton"),pauseButton=document.getElementById("pauseButton");
let board=createBoard(),currentPiece=null,nextPiece=null,bag=[],score=0,lines=0,level=1,dropCounter=0,dropInterval=900,lastTime=0,animationId=null,playing=false,paused=false,highScore=Number(localStorage.getItem("tetrisZenHighScore")||0);highScoreValue.textContent=String(highScore);
function createBoard(){return Array.from({length:ROWS},()=>Array(COLS).fill(null))}function shuffle(a){const c=[...a];for(let i=c.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]]}return c}function refillBag(){bag=shuffle(Object.keys(SHAPES))}function takeType(){if(!bag.length)refillBag();return bag.pop()}function makePiece(type=takeType()){return{type,matrix:SHAPES[type].map(r=>[...r]),x:Math.floor(COLS/2)-Math.ceil(SHAPES[type][0].length/2),y:0}}
function resetGame(){board=createBoard();score=0;lines=0;level=1;dropInterval=900;bag=[];currentPiece=makePiece();nextPiece=makePiece();playing=true;paused=false;updateStats();hideOverlay();draw();cancelAnimationFrame(animationId);lastTime=performance.now();animationId=requestAnimationFrame(update);pauseButton.textContent="⏸"}
function update(time=0){if(!playing)return;if(!paused){const d=time-lastTime;lastTime=time;dropCounter+=d;if(dropCounter>dropInterval)softDrop(false);draw()}else lastTime=time;animationId=requestAnimationFrame(update)}
function collide(piece,testX=piece.x,testY=piece.y,testMatrix=piece.matrix){for(let y=0;y<testMatrix.length;y++)for(let x=0;x<testMatrix[y].length;x++){if(!testMatrix[y][x])continue;const bx=testX+x,by=testY+y;if(bx<0||bx>=COLS||by>=ROWS||(by>=0&&board[by][bx]))return true}return false}
function mergePiece(){currentPiece.matrix.forEach((r,y)=>r.forEach((v,x)=>{if(v&&currentPiece.y+y>=0)board[currentPiece.y+y][currentPiece.x+x]=currentPiece.type}))}function spawnNextPiece(){currentPiece=nextPiece;currentPiece.x=Math.floor(COLS/2)-Math.ceil(currentPiece.matrix[0].length/2);currentPiece.y=0;nextPiece=makePiece();if(collide(currentPiece))endGame()}
function softDrop(addScore=true){if(!playing||paused)return;if(!collide(currentPiece,currentPiece.x,currentPiece.y+1)){currentPiece.y++;if(addScore)score++}else{mergePiece();clearLines();spawnNextPiece()}dropCounter=0;updateStats()}function hardDrop(){if(!playing||paused)return;let d=0;while(!collide(currentPiece,currentPiece.x,currentPiece.y+1)){currentPiece.y++;d++}score+=d*2;mergePiece();clearLines();spawnNextPiece();dropCounter=0;updateStats()}function move(dir){if(!playing||paused)return;if(!collide(currentPiece,currentPiece.x+dir,currentPiece.y))currentPiece.x+=dir}function rotateMatrix(m){return m[0].map((_,i)=>m.map(r=>r[i]).reverse())}function rotatePiece(){if(!playing||paused)return;const r=rotateMatrix(currentPiece.matrix);for(const o of [0,-1,1,-2,2])if(!collide(currentPiece,currentPiece.x+o,currentPiece.y,r)){currentPiece.matrix=r;currentPiece.x+=o;return}}
function clearLines(){let c=0;for(let y=ROWS-1;y>=0;y--)if(board[y].every(Boolean)){board.splice(y,1);board.unshift(Array(COLS).fill(null));c++;y++}if(c){const p=[0,100,300,500,800];score+=p[c]*level;lines+=c;level=Math.floor(lines/10)+1;dropInterval=Math.max(110,900-(level-1)*70)}}function endGame(){playing=false;cancelAnimationFrame(animationId);if(score>highScore){highScore=score;localStorage.setItem("tetrisZenHighScore",String(highScore))}updateStats();showOverlay("Fin del juego",`Puntaje final: ${score}`,"Jugar otra vez")}function togglePause(){if(!playing)return;paused=!paused;pauseButton.textContent=paused?"▶":"⏸";if(paused)showOverlay("Juego pausado","Pulsa continuar cuando estés lista.","Continuar");else{hideOverlay();lastTime=performance.now()}}function updateStats(){scoreValue.textContent=String(score);levelValue.textContent=String(level);linesValue.textContent=String(lines);highScoreValue.textContent=String(highScore)}
function shadeColor(hex,a){const v=parseInt(hex.replace("#",""),16),r=Math.max(0,Math.min(255,(v>>16)+a)),g=Math.max(0,Math.min(255,((v>>8)&255)+a)),b=Math.max(0,Math.min(255,(v&255)+a));return`rgb(${r},${g},${b})`}function drawCell(c,x,y,color,size=BLOCK){const g=c.createLinearGradient(x*size,y*size,(x+1)*size,(y+1)*size);g.addColorStop(0,color);g.addColorStop(1,shadeColor(color,-26));c.fillStyle=g;c.fillRect(x*size+1.5,y*size+1.5,size-3,size-3);c.strokeStyle="rgba(255,255,255,.28)";c.strokeRect(x*size+2.5,y*size+2.5,size-5,size-5)}function drawGrid(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#0b1220";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle="rgba(148,163,184,.08)";for(let x=0;x<=COLS;x++){ctx.beginPath();ctx.moveTo(x*BLOCK,0);ctx.lineTo(x*BLOCK,canvas.height);ctx.stroke()}for(let y=0;y<=ROWS;y++){ctx.beginPath();ctx.moveTo(0,y*BLOCK);ctx.lineTo(canvas.width,y*BLOCK);ctx.stroke()}}function drawBoard(){board.forEach((r,y)=>r.forEach((t,x)=>{if(t)drawCell(ctx,x,y,COLORS[t])}))}function getGhostY(){let y=currentPiece.y;while(!collide(currentPiece,currentPiece.x,y+1))y++;return y}function drawPiece(piece,ghost=false){const gy=ghost?getGhostY():piece.y;piece.matrix.forEach((r,y)=>r.forEach((v,x)=>{if(!v)return;if(ghost){ctx.fillStyle="rgba(255,255,255,.08)";ctx.fillRect((piece.x+x)*BLOCK+3,(gy+y)*BLOCK+3,BLOCK-6,BLOCK-6)}else drawCell(ctx,piece.x+x,piece.y+y,COLORS[piece.type])}))}function drawNextPiece(){nextCtx.clearRect(0,0,nextCanvas.width,nextCanvas.height);nextCtx.fillStyle="#0f172a";nextCtx.fillRect(0,0,nextCanvas.width,nextCanvas.height);if(!nextPiece)return;const s=28,m=nextPiece.matrix,w=m[0].length*s,h=m.length*s,ox=(nextCanvas.width-w)/2,oy=(nextCanvas.height-h)/2;m.forEach((r,y)=>r.forEach((v,x)=>{if(v){nextCtx.fillStyle=COLORS[nextPiece.type];nextCtx.fillRect(ox+x*s+2,oy+y*s+2,s-4,s-4)}}))}function draw(){drawGrid();drawBoard();if(currentPiece){drawPiece(currentPiece,true);drawPiece(currentPiece,false)}drawNextPiece()}function showOverlay(t,tx,b){overlayTitle.textContent=t;overlayText.textContent=tx;startButton.textContent=b;overlay.classList.add("visible")}function hideOverlay(){overlay.classList.remove("visible")}function handleAction(a){({left:()=>move(-1),right:()=>move(1),rotate:rotatePiece,down:()=>softDrop(true),drop:hardDrop}[a]?.());draw()}
document.querySelectorAll("[data-action]").forEach(b=>b.addEventListener("pointerdown",e=>{e.preventDefault();handleAction(b.dataset.action)}));document.addEventListener("keydown",e=>{if(["ArrowLeft","ArrowRight","ArrowDown","ArrowUp"," ","p","P"].includes(e.key))e.preventDefault();if(e.key==="ArrowLeft")move(-1);if(e.key==="ArrowRight")move(1);if(e.key==="ArrowDown")softDrop(true);if(e.key==="ArrowUp")rotatePiece();if(e.key===" ")hardDrop();if(e.key==="p"||e.key==="P")togglePause();draw()});startButton.addEventListener("click",()=>{if(!playing)resetGame();else if(paused)togglePause()});pauseButton.addEventListener("click",togglePause);
let sx=null,sy=null;canvas.addEventListener("touchstart",e=>{const t=e.touches[0];sx=t.clientX;sy=t.clientY},{passive:true});canvas.addEventListener("touchend",e=>{if(sx===null)return;const t=e.changedTouches[0],dx=t.clientX-sx,dy=t.clientY-sy,ax=Math.abs(dx),ay=Math.abs(dy);if(ax<20&&ay<20)rotatePiece();else if(ax>ay)move(dx>0?1:-1);else if(dy>0)hardDrop();sx=sy=null;draw()},{passive:true});draw();if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(console.error));
